### ISSUE TITLE
Example 05_character renders incorrectly

### ISSUE THREAD

**Issue by hoelzl** [hugoam/two#12]
To compile example `05_character` I had to modify the file name for the character model (the trivial patch is attached after the text.)

After doing that I get the following output instead of the expected animated character:

![2019-01-09_18-39-54](https://user-images.githubusercontent.com/35998/50917540-0bcca680-143e-11e9-8c73-0e76e5d139ae.gif)

 (Built from the latest master (00fc8af) using VS2017 on Windows 10 Pro 64 bit with GeForce GTX 1080 graphics card, driver version 417.35, 4k monitor.)

[05_example_file_name_fix.zip](https://github.com/hugoam/mud/files/2741943/05_example_file_name_fix.zip)

**Comment by hugoam** [comment]
The missing character file is due to the files being out of sync, which I fixed in https://github.com/hugoam/mud/commit/f38fdcfc88ff00e51352977de1dd8e0f47d70085.
I've had similar reports of the character skinning not working properly on GL, can you please send me the console/debug log of that one so I can check ?

**Comment by hoelzl** [comment]
Console and debug log for the OpenGL build are as follows:

[05_character_console_output.txt](https://github.com/hugoam/mud/files/2745759/05_character_console_output.txt)
[05_character_debug_output.txt](https://github.com/hugoam/mud/files/2745760/05_character_debug_output.txt)

Just like example 3, the demo works when I switch do D3D.

**Comment by hoelzl** [comment]
When building from 6ed1f1c01595ca312dbe758bc05a19ee64834c05 the output no longer looks quite as random when using OpenGL:

<img width="801" alt="05_character_d_2019-01-11_15-56-27" src="https://user-images.githubusercontent.com/35998/51041670-bcf84b80-15ba-11e9-8c7a-68ae6f0b6e2b.png">

I'm not sure how clear this is from a still image, but you can now see the ground plane and the character's base circle, and you can move the character around, but the mesh looks as if it somehow explodes around the character's origin.

**Comment by hugoam** [comment]
It took me an incredibly long amount of time to figure this out, but I think this issue is now solved.
