### ISSUE TITLE
build failing on BgfxSystem.cpp

### ISSUE THREAD

**Issue by npisanti** [hugoam/two#18]
I tried to compile two as described in `README.md` but i got those compiler errors, i'm on Debian 9:
```console
BgfxSystem.cpp
In file included from ../../../src/ctx/Context.h:10:0,
                 from ../../../src/ctx-glfw/GlfwContext.h:11,
                 from ../../../src/bgfx/BgfxSystem.h:13,
                 from ../../../src/bgfx/BgfxSystem.cpp:17:
../../../src/math/Vec.h:208:32: error: ‘two::x3’ declared as an ‘inline’ variable
  export_ constexpr inline vec3 x3 = { 1.f, 0.f, 0.f };
                                ^~
../../../src/math/Vec.h:209:32: error: ‘two::y3’ declared as an ‘inline’ variable
  export_ constexpr inline vec3 y3 = { 0.f, 1.f, 0.f };
                                ^~
../../../src/math/Vec.h:210:32: error: ‘two::z3’ declared as an ‘inline’ variable
  export_ constexpr inline vec3 z3 = { 0.f, 0.f, 1.f };
                                ^~
../../../src/math/Vec.h:212:32: error: ‘two::ZeroQuat’ declared as an ‘inline’ variable
  export_ constexpr inline quat ZeroQuat = { 0.f, 0.f, 0.f, 1.f };
                                ^~~~~~~~
../../../src/math/Vec.h:214:32: error: ‘two::Rect4’ declared as an ‘inline’ variable
  export_ constexpr inline vec4 Rect4 = { 0.f, 0.f, 1.f, 1.f };
                                ^~~~~
```

**Comment by hugoam** [comment]
This is due to two now using C++17 features, so it wouldn't compile if your compiler isn't fully C++17 compliant I think (which is probably what's happening here).

**Comment by npisanti** [comment]
yes you are right, `gcc` in debian is version 6 and version 7 is needed for c++17. I've also got `clang` and `clang-6.0` repo installed, the latter should be able to compile c++17, how can i use it to build two?

**Comment by hugoam** [comment]
You need to call genie with different parameters to use clang:
`bin/linux/genie --gcc=linux-clang gmake`
this will generate the makefiles in the folder `build/projects/linux-clang` IIRC

**Comment by npisanti** [comment]
so should it work like : `bin/linyx/genie --gcc=linux-clang-6.0` or i have to find a way for `clang` to don't use the default one (3.8)

**Comment by hugoam** [comment]
Hmmm, right, you might have to edit the script to make that work (they aren't very flexible with that for now) by adding an entry "linux-clang-6" [here](https://github.com/hugoam/two/blob/master/scripts/toolchain/toolchain.lua#L62) and [here](https://github.com/hugoam/two/blob/master/scripts/toolchain/toolchain.lua#L324)

**Comment by hugoam** [comment]
In the future we could add an option "tool-suffix" or "compiler-suffix" to make this more flexible so you don't have to mess with the toolchain file.

**Comment by npisanti** [comment]
i was able to compile, but now i get an error on a different file 
```cpp
../../../src/stl/type_traits.h:15:50: error: no template named
      'is_trivially_destructible_v' in namespace 'std'; did you mean
      'is_trivially_destructible'?
  ...bool is_trivially_destructible = std::is_trivially_destructible_v<T>;

```
should i open another issue and close this? i can fix that by changing `std::is_trivially_destructible_v<T>` to `std::is_trivially_destructible<T>()` but then i got other compile errors

**Comment by hugoam** [comment]
This is most likely a problem of C++ STL version associated to your compiler. Those helpers have been added in C++17.
Your compiler is probably using an anterior version of the STL here because of the magic ways through which `gcc` (and clang) decides what STL location it's using to compile
