### ISSUE TITLE
.gitmodules have some issues

### ISSUE THREAD

**Issue by zloop1982** [hugoam/two#23]
first : there are two modules their path is "https://github.com/hugoam/nanovg". one is "3rdparty/nanovgvg-layers",another one is "3rdparty/nanovg-layers"
second :git.exe submodule update --progress --init -- "3rdparty/nanovg"
error: pathspec '3rdparty/nanovg' did not match any file(s) known to git
this seems 3rdparty/nanovg not in the git.

**Comment by hugoam** [comment]
Indeed, we do not use nanovg anymore since a long time
I don't think this prevents from building the library, but thanks for reporting ! I cleaned up the modules file
