### ISSUE TITLE
Build failing on `yacc` error

### ISSUE THREAD

**Issue by dread-uo** [hugoam/two#8]
Hello! I've been trying to build `toy`, and had this problem. I've got no errors building `bgfx`, but had the same error trying to build the `mud-sample` as the README specifies. This is the error after running `make` for the second time - the error is the same as the first, but this second run is more legible.

```bash
➜  gmake-linux git:(master) make config=debug64
==== Building fcpp (debug64) ====
==== Building glslang (debug64) ====
==== Building glsl-optimizer (debug64) ====
yacc  ../../../mud/3rdparty/bgfx/3rdparty/glsl-optimizer/src/glsl/glcpp/glcpp-parse.y 
yacc: e - line 164 of "../../../mud/3rdparty/bgfx/3rdparty/glsl-optimizer/src/glsl/glcpp/glcpp-parse.y", syntax error
%locations
^
make[1]: *** [<builtin>: ../../../mud/3rdparty/bgfx/3rdparty/glsl-optimizer/src/glsl/glcpp/glcpp-parse.c] Error 1
make: *** [Makefile:69: glsl-optimizer] Error 2

```

I'm currently using Fedora 28, `yacc` 1.9.

Kudos for your awesome projects!

**Comment by gbbnfhb** [comment]
https://github.com/bkaradzic/bgfx/issues/304#issuecomment-92420314

**Comment by dread-uo** [comment]
@gbbnfhb , thanks, it worked!
